language: node_js
node_js:
  - "11"
cache:
  directories:
  - node_modules
before_install:
  - cd survey
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: survey/dist
  on:
    branch: master
